name: soundhex
services:
  nextjs-app:
    image: ghcr.io/vtdocker/soundhex_app:backup
    ports:
      - "8501:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
