version: '3.8'
name: soundhex
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped